# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

# [Xcodeproj] Generated duplicate UUIDs 제거
install!'cocoapods',:deterministic_uuids=>false

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      
    end
  end
end

# Available Pods
def available_pods
  
  # Pods for HumanscapeTest
  
  #Rx
  pod 'Moya/RxSwift'
  pod 'RxCocoa'
  
  #Util
  pod 'Then'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 7.0'

end

target 'HumanscapeTest' do
available_pods
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

end
